const movies = [
    {
      title: "Inception",
      fullTitle: "Inception (2010)",
      movie_year: 2010,
      categories: ["Action", "Sci-Fi", "Thriller"],
      summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
      img: 'image.png',
      imdb_id: "tt1375666",
      imdb_rating: 8.8,
      runtime: "148 min",
      language: "English",
      ytid: "YoHD9XEInc0"
    },
    {
      title: "The Matrix",
      fullTitle: "The Matrix (1999)",
      movie_year: 1999,
      categories: ["Action", "Sci-Fi"],
      summary: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      img: 'image.png',
      imdb_id: "tt0133093",
      imdb_rating: 8.7,
      runtime: "136 min",
      language: "English",
      ytid: "m8e-FF8MsqU"
    },
    {
      title: "Interstellar",
      fullTitle: "Interstellar (2014)",
      movie_year: 2014,
      categories: ["Adventure", "Drama", "Sci-Fi"],
      summary: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      img: 'image.png',
      imdb_id: "tt0816692",
      imdb_rating: 8.6,
      runtime: "169 min",
      language: "English",
      ytid: "2LqzF5WauAw"
    },
    {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
      {
        title: "Inception",
        fullTitle: "Inception (2010)",
        movie_year: 2010,
        categories: ["Action", "Sci-Fi", "Thriller"],
        summary: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        img: 'image.png',
        imdb_id: "tt1375666",
        imdb_rating: 8.8,
        runtime: "148 min",
        language: "English",
        ytid: "YoHD9XEInc0"
      },
  ];
  